sensors2ppgbp:
  0:
    D: 32
    C: 66
  1:
    D: 32
    C: 17
  2:
    D: 64
    C: 17
  3:
    D: 64
    C: 5
  4:
    D: 128
    C: 5
  5:
    D: 128
    C: 2
  6:
    D: 256
    C: 2
  7:
    D: 256
    C: 1
  8:
    D: 512
    C: 1
  9:
    D: 512
    C: 1

sensors2bcg:
  0:
    D: 32
    C: 157
  1:
    D: 32
    C: 40
  2:
    D: 64
    C: 40
  3:
    D: 64
    C: 10
  4:
    D: 128
    C: 10
  5:
    D: 128
    C: 3
  6:
    D: 256
    C: 3
  7:
    D: 256
    C: 1
  8:
    D: 512
    C: 1
  9:
    D: 512
    C: 1

ppgbp2bcg:
  0:
    D: 32
    C: 157
  1:
    D: 32
    C: 40
  2:
    D: 64
    C: 40
  3:
    D: 64
    C: 10

ppgbp2sensors:
  0:
    D: 32
    C: 66
  1:
    D: 32
    C: 17
  2:
    D: 64
    C: 17
  3:
    D: 64
    C: 5

bcg2ppgbp:
  0:
    D: 32
    C: 66
  1:
    D: 32
    C: 17
  2:
    D: 64
    C: 17
  3:
    D: 64
    C: 5
  4:
    D: 128
    C: 5
  5:
    D: 128
    C: 2
  6:
    D: 256
    C: 2
  7:
    D: 256
    C: 1

bcg2sensors:
  0:
    D: 32
    C: 157
  1:
    D: 32
    C: 40
  2:
    D: 64
    C: 40
  3:
    D: 64
    C: 10
  4:
    D: 128
    C: 10
  5:
    D: 128
    C: 3
  6:
    D: 256
    C: 3
  7:
    D: 256
    C: 1